In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  5 17:28:15 2017

@author: nlhsueh
"""

import numpy as np
c = np.arange(27).reshape(3,3,3) 
print (c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [2]:
print(c.ndim)
print( c.shape)
print(c.dtype)

3
(3, 3, 3)
int64


In [3]:
print (c[0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
a = np.array([1234])
print(a)

[1234]


In [5]:
a = np.array([[1112131415], [1617181920212223242526272829303132333435]])
print (a)

[[1112131415]
 [1617181920212223242526272829303132333435]]


In [6]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [7]:
print (a[:2, :2])

[[0 1]
 [4 5]]


In [8]:
print (a[:2, :])

[[0 1 2 3]
 [4 5 6 7]]


In [9]:
print (a[::2, :])

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [10]:
print (a[:, 1:3])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
